version: '3'
services:
  my_item_repository:
    image: villirn/hgop:${GIT_COMMIT}
    ports:
    - '3000:3000'
    depends_on:
    - my_postgres_container
    environment:
      POSTGRES_HOST: 'my_postgres_container'
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'game'
      POSTGRES_PASSWORD: '12345'
      PORT: 3000
  my_postgres_container:
    image: postgres
    environment:
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'game'
      POSTGRES_PASSWORD: '12345'
  my_datadog_container:
      image: datadog/agent:latest
      environment:
        - DD_API_KEY=fd12f8e381c95b982c535cb9247c8d33
        - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /proc/:/host/proc/:ro
        - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
