version: '3'
services:
  my_item_repository:
    image: villirn/hgop:${GIT_COMMIT}
    ports:
    - '3000:3000'
    depends_on:
    - my_postgres_container
    environment:
      POSTGRES_HOST: 'my_postgres_container'
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'game'
      POSTGRES_PASSWORD: '12345'
      PORT: 3000
  my_postgres_container:
    image: postgres
    environment:
      POSTGRES_DB: 'game_database'
      POSTGRES_USER: 'game'
      POSTGRES_PASSWORD: '12345'
